version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  target-branch: develop
  reviewers:
  - ewohltman
  assignees:
  - ewohltman
  labels:
  - dependencies
  ignore:
  - dependency-name: github.com/prometheus/common
    versions:
    - 0.16.0
    - 0.17.0
    - 0.18.0
    - 0.19.0
    - 0.20.0
    - 0.21.0
