---
name: pull_request
"on": [pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.15
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
        id: go

      - name: Check out code
        uses: actions/checkout@v2

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.31

      - name: Run tests
        run: make test

      - name: Run test coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PATH="${PATH}:$(go env GOPATH)/bin"

          GO111MODULE=off go get -u github.com/mattn/goveralls

          goveralls -coverprofile=coverage.out -service=github

      - name: Build binary
        run: make build

      - name: Build Docker image
        run: make image
